# Generated by Django 3.0.5 on 2020-04-26 06:52

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('initiative_id', models.AutoField(help_text='Auto-Generated Id', primary_key=True, serialize=False)),
                ('initiative_name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('workforce_size', models.CharField(blank=True, max_length=50, null=True)),
                ('parent_entity', models.CharField(blank=True, max_length=100, null=True)),
                ('location_hash', models.CharField(blank=True, help_text='Generates a Hash for a pair of (City, Country) to match duplicates', max_length=100, null=True)),
                ('location_city', models.CharField(blank=True, max_length=50, null=True)),
                ('location_country', models.CharField(blank=True, max_length=50, null=True)),
                ('googlemaps_url', models.URLField(blank=True, help_text='Map URL of (City, Country) to show on a World Map', null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True, help_text='Date added in the Database')),
                ('start_date', models.DateTimeField(blank=True, help_text='Project Start Date', null=True)),
                ('start_year', models.DateTimeField(blank=True, help_text='Project Start Year', null=True)),
                ('is_active', models.BooleanField(default=None, help_text='Active Status of Initiative', null=True)),
                ('labels', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'ordering': ['initiative_id'],
            },
        ),
    ]
