# Generated by Django 3.2 on 2021-04-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreEngine', '0002_auto_20210425_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='down_votes_total',
        ),
        migrations.RemoveField(
            model_name='posts',
            name='up_votes_total',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='down_vote',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='up_vote',
        ),
        migrations.AddField(
            model_name='posts',
            name='vote_count',
            field=models.SmallIntegerField(blank=True, default=0, help_text='A total of votes received so far.', null=True),
        ),
        migrations.AddField(
            model_name='votes',
            name='vote',
            field=models.BooleanField(default=True, help_text='Vote Up or down on the basis of if post is helpful.'),
        ),
    ]
