# Generated by Django 3.0.5 on 2020-04-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coreEngine', '0002_auto_20200427_0032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='initiative',
            name='location_hash',
        ),
    ]
