# Generated by Django 3.0.5 on 2020-04-28 06:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('coreEngine', '0003_remove_initiative_location_hash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initiative',
            old_name='start_date',
            new_name='date_started',
        ),
        migrations.RenameField(
            model_name='initiative',
            old_name='start_year',
            new_name='year_started',
        ),
        migrations.RemoveField(
            model_name='initiative',
            name='added_on',
        ),
        migrations.AddField(
            model_name='initiative',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Date created in the Database'),
            preserve_default=False,
        ),
    ]
