# Generated by Django 3.2 on 2021-04-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreEngine', '0004_alter_posts_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['date_updated']},
        ),
        migrations.RemoveField(
            model_name='posts',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='votes',
            name='user_ip',
        ),
        migrations.AddField(
            model_name='posts',
            name='date_updated',
            field=models.DateTimeField(auto_now=True, help_text='Last updated timestamp'),
        ),
    ]
