# Generated by Django 3.0.5 on 2020-04-28 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.AutoField(help_text='Auto-Generated Id', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('article_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_crawled', models.DateTimeField()),
                ('date_published', models.DateTimeField()),
                ('is_processed', models.BooleanField(default=False, help_text='Whether the article_text is processed for initiatives or not.')),
            ],
            options={
                'ordering': ['date_created'],
            },
        ),
    ]
